server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: client-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/hoteloom-app

eureka:
  instance:
    hostname: localhost
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        requestInterceptors:
          com.vmelik.client.client.interceptor.TokenAuthInterceptor

services:
  hotel-service:
    url: http://localhost:8081/api/hotels