server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/hoteloom-app

services:
  hotel-service:
    url: http://localhost:8081/api/hotels