server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: client-service
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/hoteloom-app
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/hoteloom-app

services:
  hotel-service:
    url: http://localhost:8081/api/hotels