server:
  port: ${SERVER_PORT}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: hotel
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**
        - id: test
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}