apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-volume-claim
  labels:
    app: postgres-keycloak
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi