spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hoteloom}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:superadmin}
    password: ${DB_PASSWORD:superpassword}