apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: hotel-service:latest
          imagePullPolicy: Never # Never is for local minikube testing
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: common-values
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/hoteloom?currentSchema=hotel_service
