apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: hotel-service:latest
          imagePullPolicy: Never # Never is for local minikube testing
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: standalone
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8080/eureka
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/hoteloom?currentSchema=hotel_service
            - name: OAUTH2_ISSUER
              value: http://keycloak:8080/realms/hoteloom-app
