server:
  port: ${SERVER_PORT}

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hoteloom?currentSchema=hotel_service
    driver-class-name: org.postgresql.Driver
    username: hotel_service_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/hoteloom-app

eureka:
  instance:
    hostname: localhost
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /api-docs