server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoteloom?currentSchema=hotel_service
    driver-class-name: org.postgresql.Driver
    username: hotel_service_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/hoteloom-app

springdoc:
  api-docs:
    path: /api-docs