version: "3.9"
name: local_environment

x-common-variables: &common-variables
  SPRING_PROFILES_ACTIVE: standalone
  EUREKA_SERVER_URL: http://eureka-server:8761/eureka
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hoteloom
  OAUTH2_ISSUER: http://keycloak:8088/realms/hoteloom-app

services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_DB: "hoteloom"
      POSTGRES_USER: "superadmin"
      POSTGRES_PASSWORD: "superpassword"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - hoteloom-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-keycloak:
    container_name: postgres-keycloak
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:25.0.0
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_IMPORT: /keycloak/realm.json
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
    ports:
      - "8088:8080"
      - "9001:9000"
    depends_on:
      - postgres-keycloak
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json

  eureka-server:
    container_name: eureka-server
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      SERVER_PORT: 8761
    ports:
      - "8761:8761"

  gateway-service:
    container_name: gateway-service
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      SERVER_PORT: 8888
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server

  admin-service:
    container_name: admin-service
    build:
      context: ../admin-service
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hoteloom
    depends_on:
      - postgres

  client-service:
    container_name: client-service
    build:
      context: ../client-service
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

  hotel-service:
    container_name: hotel-service
    build:
      context: ../hotel-service
      dockerfile: Dockerfile
    environment:
      <<: *common-variables
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hoteloom?currentSchema=hotel_service
    ports:
      - "8082:8082"

volumes:
  hoteloom-db-data:
  keycloak_db_data:
    driver: local