apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-keycloak-secret
  labels:
    app: postgres-keycloak
data: # TODO move to secrets
  POSTGRES_DB: keycloakdb
  POSTGRES_USER: keycloakuser
  POSTGRES_PASSWORD: keycloakpass