server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
#  instance:
#    hostname: localhost
  client:
    register-with-eureka: false # no need to register itself in standalone mode
    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/